### ISSUE TITLE
GPL v3 from errbot ?

### ISSUE THREAD

**Issue by gbin** [kongluoxing/TomBot#3]
Tombot looks awesome and is at least a partial fork from errbot (http://errbot.net).
This is welcomed and encouraged by the GPL v3 license errbot has been release with.

The only constraint doing that is simply to keep the same license (see http://www.gnu.org/licenses/gpl-faq.en.html#GPLRequireSourcePostedPublic).

May I kindly ask you to use https://github.com/gbin/err/blob/master/COPYING for tombot instead of https://github.com/kongluoxing/TomBot/blob/master/LICENSE ?

Thanks a lot in advance.

**Comment by kongluoxing** [comment]
Of course, I write tombot just for fun, so I never care about the license :)
